### PR TITLE
Adding new validator class called IterableValidator

### PR DESCRIPTION
**Pull request by Aparna-BS**
Adding a new validator class in validators.py for validating iterables. This class checks the contents of iterators like list, tuple, dict or set.

Methods available for IterableValidator are:
1) empty_iterable_checker() - Verifies if the iterable parameter can be empty or not.
2) element_type_checker() - Verifies if the elements of the iterable are of required data type.
3) elements_sign_checker() - Verifies if the elements of the iterable are positive or negative.

### CODE REVIEW

**Comment by uzumaxy** [comment]
Hey @Aparna-BS ,
Thank you for your contribution! I'll be happy to merge this feature and deploy it to PyPi.

Before that, I also wanted to ask your opinion about the "sign (str)" parameter. Right now it accepts the string:
- "positive" - in case if we need to allow only positive numbers;
- "negative" - in case if we need to allow only negative numbers.

So right now it's working in this way:
```
positiveValuesValidator = IterableValidator(sign='positive')
negativeValuesValidator = IterableValidator(sign='negative')
```

How do you think, would it be better to use min/max parameters instead of this one? We may introduce these two parameters which will accept the number value and it will help us to perform such checks as you're already doing with via the "sign" option, but min/max will be a bit more flexible. For example, we may restrict allowed values to some specific range of values, such as (min=0, max=100) or (min=None, max=0) or any other values range.
Also, as far as I know, it's a bad practice to use string values such as "positive" or "negative" instead of Enum. So the approach with min/max might be better in this case as well.

I'm suggesting use the min/max options instead of the "sign" option in the following way (please compare it with the code above):

```
positiveValuesValidator = IterableValidator(min=0)
negativeValuesValidator = IterableValidator(max=0)
waterTemperatureValidator = IterableValidator(min=0, max=100)
```

Please let me know what do you think about it.

Thanks!

**Comment by ankitagarwal** [comment]
@Aparna-BS I agree with comments from @uzumaxy 

Also, @uzumaxy What do you think of making "Validators" into a folder with one class per file as it will increase readability and make it easy for us to add more validators in the future?

Thanks

**Comment by Aparna-BS** [comment]
@uzumaxy Thanks for your feedback. Totally agree with your comments. I have updated the Pull Request with the changes you suggested. 

Thanks,
Aparna

**Review by uzumaxy — APPROVED** [review]

**Comment by uzumaxy** [comment]
Hey @ankitagarwal,
Yeah, that's definitely a good idea, I've mentioned it (in order to keep in track) in the #20 and will try to handle it soon. Thanks!

**Comment by uzumaxy** [comment]
Hey @Aparna-BS ,
Thank you for applying these changes, you're making an amazing contribution 👍 I'll be happy to deploy your new Validator in the next release!

**Pull request merged**
